detect_format:
  description: "Detect if the file is binary, Python, or JavaScript."
  expected_output: "Language and file type classification (e.g. 'text/javascript')."
  agent: "input_parser_agent"

obfuscate_code:
  description: "Apply obfuscation to the code using AST or pattern-based transformations."
  expected_output: "Obfuscated code with renamed variables and altered structure."
  agent: "obfuscation_agent"

deobfuscate_code:
  description: "Attempt to revert obfuscation and restore clarity to code."
  expected_output: "Readable code resembling the original version."
  agent: "deobfuscation_agent"

verify_correctness:
  description: "Compare functional output of original and deobfuscated versions."
  expected_output: "Validation of correctness and confirmation of preserved behavior."
  agent: "verifier_agent"
